{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "@allure.feature('test_broken')\n    def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\nstudy.py:22: Exception"}, "start": 1663754643542, "stop": 1663754643542, "uuid": "da94631a-48a1-408f-94a1-fba8231fa8b0", "historyId": "ca23a3b0355b6265a46cddceeb9ffeca", "testCaseId": "8f86bed1a50ad039e7b36d28982c5b3d", "fullName": "study#test_broken", "labels": [{"name": "feature", "value": "test_broken"}, {"name": "suite", "value": "study"}, {"name": "host", "value": "CD-N00013"}, {"name": "thread", "value": "6956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "study"}]}